
package de.htwg_konstanz.ebus.wholesaler.ws.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalogServicePortType", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/product_catalog")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalogServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns de.htwg_konstanz.ebus.wholesaler.ws.ws.ProductCatalogServiceResponse
     * @throws ProductCatalogServiceFault
     */
    @WebMethod
    @WebResult(name = "ProductCatalogServiceResponse", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/product_catalog", partName = "response")
    public ProductCatalogServiceResponse getProductCatalog(
        @WebParam(name = "ProductCatalogServiceRequest", targetNamespace = "http://www.htwg-konstanz.de/ebsf/ws/product_catalog", partName = "request")
        ProductCatalogServiceRequest request)
        throws ProductCatalogServiceFault
    ;

}
