
package de.htwg_konstanz.ebus.wholesaler.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "updateProduct_WebService", targetNamespace = "http://www.example.org/updateCatalog/", wsdlLocation = "file:/C:/Users/Fuchs/Desktop/updateCatalog.wsdl")
public class UpdateProductWebService
    extends Service
{

    private final static URL UPDATEPRODUCTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException UPDATEPRODUCTWEBSERVICE_EXCEPTION;
    private final static QName UPDATEPRODUCTWEBSERVICE_QNAME = new QName("http://www.example.org/updateCatalog/", "updateProduct_WebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Fuchs/Desktop/updateCatalog.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPDATEPRODUCTWEBSERVICE_WSDL_LOCATION = url;
        UPDATEPRODUCTWEBSERVICE_EXCEPTION = e;
    }

    public UpdateProductWebService() {
        super(__getWsdlLocation(), UPDATEPRODUCTWEBSERVICE_QNAME);
    }

    public UpdateProductWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPDATEPRODUCTWEBSERVICE_QNAME, features);
    }

    public UpdateProductWebService(URL wsdlLocation) {
        super(wsdlLocation, UPDATEPRODUCTWEBSERVICE_QNAME);
    }

    public UpdateProductWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPDATEPRODUCTWEBSERVICE_QNAME, features);
    }

    public UpdateProductWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpdateProductWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UpdateCatalogPort
     */
    @WebEndpoint(name = "updateProduct_SOAP")
    public UpdateCatalogPort getUpdateProductSOAP() {
        return super.getPort(new QName("http://www.example.org/updateCatalog/", "updateProduct_SOAP"), UpdateCatalogPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UpdateCatalogPort
     */
    @WebEndpoint(name = "updateProduct_SOAP")
    public UpdateCatalogPort getUpdateProductSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/updateCatalog/", "updateProduct_SOAP"), UpdateCatalogPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPDATEPRODUCTWEBSERVICE_EXCEPTION!= null) {
            throw UPDATEPRODUCTWEBSERVICE_EXCEPTION;
        }
        return UPDATEPRODUCTWEBSERVICE_WSDL_LOCATION;
    }

}
