
package de.htwg_konstanz.ebus.wholesaler.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "updateCatalog_Port", targetNamespace = "http://www.example.org/updateCatalog/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UpdateCatalogPort {


    /**
     * 
     * @param request
     * @return
     *     returns de.htwg.UpdateResponseT
     * @throws UpdateCatalogFault
     */
    @WebMethod(action = "http://www.example.org/updateCatalog/updateCatalog")
    @WebResult(name = "updateResponse", targetNamespace = "http://www.example.org/updateCatalog/", partName = "response")
    public UpdateResponseT updateCatalog(
        @WebParam(name = "updateRequest", targetNamespace = "http://www.example.org/updateCatalog/", partName = "request")
        UpdateRequestT request)
        throws UpdateCatalogFault
    ;

}
